In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# problems = pd.read_csv('problems_features.csv')
# tags = problems['tags'].unique()

# [one_hot(d, 50) for d in tags[1:]]

# max_length = 4
# padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
# print(padded_docs)

In [ ]:
# max_length = 4
# padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
# print(padded_docs)

In [ ]:
# model = Sequential()
# e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
# model.add(e)
# model.add(Flatten())


In [34]:
# results = pd.read_csv('data/train/train_submissions.csv')
# test = pd.read_csv('data/test_submissions_NeDLEvX.csv')
# users = pd.read_csv('cleaned_users.csv')
problems = pd.read_csv('problems_features.csv')
# results.shape, test.shape, problems.shape, users.shape

In [173]:
test = pd.read_csv('data/test_submissions_NeDLEvX.csv')


In [4]:
users.head()

Unnamed: 0    user_id  submission_count  problem_solved  contribution  \
0           0  user_3311                47              40             0   
1           1  user_3028                63              52             0   
2           2  user_2268               226             203            -8   
3           3   user_480               611             490             1   
4           4   user_650               504             479            12   

   follower_count  max_rating   rating          rank  rank_enc  \
0               4     348.337  330.849  intermediate         3   
1              17     405.677  339.450  intermediate         3   
2              24     307.339  284.404      beginner         1   
3              94     525.803  471.330      advanced         0   
4               4     548.739  486.525      advanced         0   

   contribution_abs  
0                 0  
1                 0  
2                 8  
3                 1  
4                12

In [5]:
problems.columns

Index(['Unnamed: 0', 'problem_id', 'level_type', 'points', 'tags', 'tag_dict',
       'tag_vect'],
      dtype='object')

In [6]:
users.columns

Index(['Unnamed: 0', 'user_id', 'submission_count', 'problem_solved',
       'contribution', 'follower_count', 'max_rating', 'rating', 'rank',
       'rank_enc', 'contribution_abs'],
      dtype='object')

In [ ]:
temp = pd.concat([test, results], axis=0, ignore_index=True)
df.pivot_table('col3',index='col1',columns='col2')
np.argwhere(df.notnull().values)

In [7]:
users.head()

Unnamed: 0    user_id  submission_count  problem_solved  contribution  \
0           0  user_3311                47              40             0   
1           1  user_3028                63              52             0   
2           2  user_2268               226             203            -8   
3           3   user_480               611             490             1   
4           4   user_650               504             479            12   

   follower_count  max_rating   rating          rank  rank_enc  \
0               4     348.337  330.849  intermediate         3   
1              17     405.677  339.450  intermediate         3   
2              24     307.339  284.404      beginner         1   
3              94     525.803  471.330      advanced         0   
4               4     548.739  486.525      advanced         0   

   contribution_abs  
0                 0  
1                 0  
2                 8  
3                 1  
4                12

### Encoding all user and prob ids

In [175]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

u_ids = list(users.user_id.values) + list(results.user_id.values) + list(test.user_id.values)
p_ids = list(problems.problem_id.values) + list(results.problem_id.values) + list(test.problem_id.values)

enc.fit(u_ids)
users['user_id_enc'] = enc.transform(users.user_id)
results['user_id_enc'] = enc.transform(results.user_id)
test['user_id_enc'] = enc.transform(test.user_id)

enc.fit(p_ids)
problems['problem_id_enc'] = enc.transform(problems.problem_id)
results['problem_id_enc'] = enc.transform(results.problem_id)
test['problem_id_enc'] = enc.transform(test.problem_id)

In [14]:
cols = users.columns
cols

Index(['Unnamed: 0', 'user_id', 'submission_count', 'problem_solved',
       'contribution', 'follower_count', 'max_rating', 'rating', 'rank',
       'rank_enc', 'contribution_abs', 'user_id_enc'],
      dtype='object')

In [87]:
# plt.plot(users[cols[idx]])
# plt.title(cols[idx])
# idx += 1

## Replacing the outliers with the median of that feature

In [85]:
cols = ['submission_count', 'problem_solved',
       'contribution_abs', 'follower_count', 'max_rating', 'rating']
for idx in cols:
    mean, std = users[idx].mean(), users[idx].std()
    median = users[idx].loc[(users[idx] - mean).abs() < 3*std].median()
    users[idx +'new'] = np.where((users[idx] - mean).abs() > 3*std, median,users[idx])
    

(299.4810977317278, 366.10288671657946, 164.0)

In [92]:
problems.columns

Index(['Unnamed: 0', 'problem_id', 'level_type', 'points', 'tags', 'tag_dict',
       'tag_vect', 'problem_id_enc'],
      dtype='object')

In [86]:
users.head()

Unnamed: 0    user_id  submission_count  problem_solved  contribution  \
0           0  user_3311                47              40             0   
1           1  user_3028                63              52             0   
2           2  user_2268               226             203            -8   
3           3   user_480               611             490             1   
4           4   user_650               504             479            12   

   follower_count  max_rating   rating          rank  rank_enc  \
0               4     348.337  330.849  intermediate         3   
1              17     405.677  339.450  intermediate         3   
2              24     307.339  284.404      beginner         1   
3              94     525.803  471.330      advanced         0   
4               4     548.739  486.525      advanced         0   

   contribution_abs  user_id_enc  testing  submission_countnew  \
0                 0         2570     47.0                 47.0   
1                 0         2255     63.0                 63.0   
2                 8         1410    226.0                226.0   
3                 1         2995    611.0                611.0   
4                12         3184    504.0                504.0   

   problem_solvednew  contribution_absnew  follower_countnew  max_ratingnew  \
0               40.0                  0.0                4.0        348.337   
1               52.0                  0.0               17.0        405.677   
2              203.0                  8.0               24.0        307.339   
3              490.0                  1.0               94.0        525.803   
4              479.0                 12.0                4.0        548.739   

   ratingnew  
0    330.849  
1    339.450  
2    284.404  
3    471.330  
4    486.525

In [98]:
problems['level_type'] = problems['level_type'].fillna('O')

In [99]:
enc.fit(problems['level_type'])
problems['level_type_enc'] = enc.transform(problems['level_type'])

In [100]:
problems.head()

Unnamed: 0 problem_id level_type  points  \
0           0  prob_3649          H     NaN   
1           1  prob_6191          A     NaN   
2           2  prob_2020          F     NaN   
3           3   prob_313          A   500.0   
4           4   prob_101          A   500.0   

                                  tags  \
0                                  NaN   
1                                  NaN   
2                                  NaN   
3                greedy,implementation   
4  constructive algorithms,greedy,math   

                                        tag_dict  \
0                                            NaN   
1                                            NaN   
2                                            NaN   
3                   ['greedy', 'implementation']   
4  ['constructive algorithms', 'greedy', 'math']   

                                            tag_vect  problem_id_enc  \
0                                                NaN            2944   
1                                                NaN            5769   
2                                                NaN            1136   
3    (0, 35)\t0.643835105031232\n  (0, 33)\t0.765...            2368   
4    (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40...              13   

   level_type_enc  
0               7  
1               0  
2               5  
3               0  
4               0

In [105]:
problems['tags'].fillna('The')[:5]

0                                    The
1                                    The
2                                    The
3                  greedy,implementation
4    constructive algorithms,greedy,math
Name: tags, dtype: object

In [103]:
problems['tags_list'] = problems['tags'].fillna('The')

## convert tags into sequnce

In [106]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.


In [114]:
tags = problems['tags_list']#.unique()

[one_hot(d, 50) for d in tags][:6]


[[33], [33], [33], [28, 13], [47, 14, 28, 39], [33]]

In [121]:
problems['tags_list_seq'] = problems['tags_list'].map(lambda x: one_hot(x,10))

In [ ]:
pad_sequences([one_hot(d, 50) for d in tags], maxlen=5, padding='post')

In [115]:
pads = pad_sequences([one_hot(d, 50) for d in tags], maxlen=5, padding='post')[:6]

array([[33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [28, 13,  0,  0,  0],
       [47, 14, 28, 39,  0],
       [33,  0,  0,  0,  0]], dtype=int32)

In [141]:
pads = pad_sequences([one_hot(d, 50) for d in tags], maxlen=5, padding='post')

In [144]:
pads_list = []
for i in range(pads.shape[0]):
#     print(pads[i])
    pads_list.append(list(pads[i]))

In [150]:
test = pd.Series(pads_list)
problems['tags_list_seq_pad'] = test.values

In [154]:
problems.head()

Unnamed: 0 problem_id level_type  points  \
0           0  prob_3649          H     NaN   
1           1  prob_6191          A     NaN   
2           2  prob_2020          F     NaN   
3           3   prob_313          A   500.0   
4           4   prob_101          A   500.0   

                                  tags  \
0                                  NaN   
1                                  NaN   
2                                  NaN   
3                greedy,implementation   
4  constructive algorithms,greedy,math   

                                        tag_dict  \
0                                            NaN   
1                                            NaN   
2                                            NaN   
3                   ['greedy', 'implementation']   
4  ['constructive algorithms', 'greedy', 'math']   

                                            tag_vect  problem_id_enc  \
0                                                NaN            2944   
1                                                NaN            5769   
2                                                NaN            1136   
3    (0, 35)\t0.643835105031232\n  (0, 33)\t0.765...            2368   
4    (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40...              13   

   level_type_enc                            tags_list tags_list_seq  \
0               7                                  The           [4]   
1               0                                  The           [4]   
2               5                                  The           [4]   
3               0                greedy,implementation        [3, 3]   
4               0  constructive algorithms,greedy,math  [9, 1, 3, 7]   

     tags_list_seq_pad  
0     [33, 0, 0, 0, 0]  
1     [33, 0, 0, 0, 0]  
2     [33, 0, 0, 0, 0]  
3    [28, 13, 0, 0, 0]  
4  [47, 14, 28, 39, 0]

### Drop unnecaasry columns

In [185]:
import gc
del users,problems,test,results,testing
gc.collect()

543

In [193]:
users = pd.read_csv( 'users_feature_encoded_before_drop.csv')
problems = pd.read_csv( 'problems_feature_encoded_before_drop.csv')
results = pd.read_csv( 'results_feature_encoded_before_drop.csv')
tests = pd.read_csv( 'test_feature_encoded_before_drop.csv')

In [200]:
tests.columns

Index(['Unnamed: 0', 'ID', 'user_id', 'problem_id', 'user_id_enc',
       'problem_id_enc'],
      dtype='object')

In [202]:
u_ids = ['Unnamed: 0', 'Unnamed: 0.1', 'user_id', 'submission_count',
       'problem_solved', 'contribution', 'follower_count', 'max_rating',
       'rating', 'rank', 'contribution_abs','testing']
p_ids = ['Unnamed: 0', 'Unnamed: 0.1', 'problem_id', 'level_type', 'points',
         'tag_dict', 'tag_vect','tags_list', 'tags_list_seq']
r_ids = ['Unnamed: 0', 'user_id', 'problem_id']
t_ids = ['Unnamed: 0', 'ID', 'user_id', 'problem_id']

In [203]:
users.drop(u_ids, axis=1, inplace=True)
problems.drop(p_ids, axis=1, inplace=True)
results.drop(r_ids, axis=1, inplace=True)
tests.drop(t_ids, axis=1, inplace=True)

In [205]:
users.columns.shape, problems.columns.shape, results.columns.shape, tests.columns.shape

((8,), (4,), (3,), (2,))

In [206]:
users.head()

rank_enc  user_id_enc  submission_countnew  problem_solvednew  \
0         3         2570                 47.0               40.0   
1         3         2255                 63.0               52.0   
2         1         1410                226.0              203.0   
3         0         2995                611.0              490.0   
4         0         3184                504.0              479.0   

   contribution_absnew  follower_countnew  max_ratingnew  ratingnew  
0                  0.0                4.0        348.337    330.849  
1                  0.0               17.0        405.677    339.450  
2                  8.0               24.0        307.339    284.404  
3                  1.0               94.0        525.803    471.330  
4                 12.0                4.0        548.739    486.525

In [207]:
results.head()

attempts_range  user_id_enc  problem_id_enc
0               1         1468            6120
1               3         2854            2216
2               1          669            4525
3               1         1397            6216
4               1         1470            2845

In [209]:
rating_temp = pd.merge(results,users,on='user_id_enc',how='inner')

In [211]:
rating_temp.shape

(155295, 10)

In [212]:
rating_temp2 = pd.merge(rating_temp, problems,on='problem_id_enc',how='inner')

In [213]:
rating_temp2.head()

attempts_range  user_id_enc  problem_id_enc  rank_enc  submission_countnew  \
0               1         1468            6120         1                 53.0   
1               2         1013            6120         1                240.0   
2               2          917            6120         1                370.0   
3               1         3455            6120         1                318.0   
4               1         3326            6120         3                463.0   

   problem_solvednew  contribution_absnew  follower_countnew  max_ratingnew  \
0               47.0                  0.0                1.0        307.913   
1              218.0                  0.0               50.0        319.954   
2              336.0                 10.0               30.0        307.339   
3              286.0                  0.0               20.0        304.186   
4              410.0                  0.0               39.0        374.713   

   ratingnew     tags  level_type_enc tags_list_seq_pad  
0    206.709  strings               1   [6, 0, 0, 0, 0]  
1    291.284  strings               1   [6, 0, 0, 0, 0]  
2    295.585  strings               1   [6, 0, 0, 0, 0]  
3    191.514  strings               1   [6, 0, 0, 0, 0]  
4    374.713  strings               1   [6, 0, 0, 0, 0]

In [215]:
rating_temp2.to_csv('merged_all_feature_encoded_after_drop.csv',index=None)

In [216]:
rating_temp2.isnull().sum()

attempts_range             0
user_id_enc                0
problem_id_enc             0
rank_enc                   0
submission_countnew        0
problem_solvednew          0
contribution_absnew        0
follower_countnew          0
max_ratingnew              0
ratingnew                  0
tags                   15427
level_type_enc             0
tags_list_seq_pad          0
dtype: int64

In [218]:
rating_temp2.user_id_enc.unique().shape, rating_temp2.problem_id_enc.unique().shape

((3529,), (5776,))

In [222]:
rating_temp3 = rating_temp2.dropna()

In [221]:
rating_temp2.shape,rating_temp2.dropna().shape

((155295, 13), (139868, 13))

In [223]:
rating_temp3.to_csv('merged_all_feature_encoded_after_drop_non_null.csv',index=None)

In [230]:
rating_temp3.values[:,:3]

array([[1, 1468, 6120],
       [2, 1013, 6120],
       [2, 917, 6120],
       ...,
       [1, 1294, 915],
       [1, 1294, 6472],
       [1, 3037, 1372]], dtype=object)

In [233]:
# del users, problems, results, tests, rating_temp, rating_temp2, rating_temp3
# gc.collect()

In [6]:
# data = rating_temp3


# STARTED FROM HERE

In [2]:
data = pd.read_csv('merged_all_feature_encoded_after_drop_non_null.csv')

In [4]:
data.columns

Index(['attempts_range', 'user_id_enc', 'problem_id_enc', 'rank_enc',
       'submission_countnew', 'problem_solvednew', 'contribution_absnew',
       'follower_countnew', 'max_ratingnew', 'ratingnew', 'tags',
       'level_type_enc', 'tags_list_seq_pad'],
      dtype='object')

## dataset generate function

In [11]:
def generate_dataset(dataset, batch_size):
    ''' return dataset for users, problems, users-info, 
        dataset has columns: ['attempts_range', 'user_id_enc', 'problem_id_enc', 'rank_enc',
                               'submission_countnew', 'problem_solvednew', 'contribution_absnew',
                               'follower_countnew', 'max_ratingnew', 'ratingnew', 'tags',
                               'level_type_enc', 'tags_list_seq_pad'], dtype='object')
    users    ==>> [batch,N]
    problems ==>> [batch,M]
    user-info==>> [batch,omega_u]
    prob-info==>> [batch,omega_v]
    label    ==>> [batch,label]
    '''
    N = dataset['user_id_enc'].unique().shape[0]
    M = 5776#dataset['problem_id_enc'].unique().shape[0]
    label_shape = dataset['attempts_range'].unique().shape[0]
    
    idx = np.random.randint(dataset.shape[0],size=(batch_size))
    temp = dataset.values[idx]
#     users = temp[:,:3]# first three columns
#     users_info = temp[:,3:10]
#     problems_info = temp[:,11:]
#     problems_info[:,1] = problems_info[:,1].astype(int)
    
#     # user one-hot matrix
#     users = np.zeros((batch_size,N))
#     users[np.arange(batch_size), temp[:,1].astype(int)[0]] = 1  #one-hot vectors
    
#     # problems one-hot matrix
#     problems = np.zeros((batch_size,M))
#     problems[np.arange(batch_size), temp[:,2].astype(int)[0]] = 1
    
#     # label one-hot matrix
#     labels = np.zeros((batch_size,label_shape))
#     labels[np.arange(batch_size),temp[:,0].astype(int)[0]] = 1
                          
    return temp#users, problems, labels, users_info, problems_info

In [294]:
users, problems, labels, users_info, problems_info = generate_dataset(dataset=data, batch_size=2)
users.shape, problems.shape, labels.shape, users_info.shape, problems_info.shape

((2, 3526), (2, 5776), (2, 6), (2, 7), (2, 2))

In [310]:
# Convert a sequence of object data-type into array  of int data-type

# I have array of this following shape and dtype:

#     array([[1, '[13, 39, 0, 0, 0]'],
#            [2, '[9, 31, 5, 0, 0]']], dtype=object)

# I want it to merge both into one simple array with float dtype 

#     array([[1, 13, 39, 0, 0, 0],
#            [2, 9, 31, 5, 0, 0]], dtype=float)

# Please, if someone can help me?

array([[1, '[13, 39, 0, 0, 0]'],
       [2, '[9, 31, 5, 0, 0]']], dtype=object)

In [12]:
temp = generate_dataset(dataset=data, batch_size=2)
temp

array([[1, 3291, 2135, 1, 49.0, 40.0, 0.0, 11.0, 324.255, 265.482,
        'brute force,implementation', 0, '[15, 17, 13, 0, 0]'],
       [1, 1916, 5852, 3, 999.0, 968.0, 14.0, 30.0, 404.53, 383.028,
        'math', 0, '[39, 0, 0, 0, 0]']], dtype=object)

In [13]:
temp.shape

(2, 13)

In [26]:
a = np.array([[33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [28, 13,  0,  0,  0],
       [47, 14, 28, 39,  0],
       [33,  0,  0,  0,  0]])

In [27]:
a

array([[33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [33,  0,  0,  0,  0],
       [28, 13,  0,  0,  0],
       [47, 14, 28, 39,  0],
       [33,  0,  0,  0,  0]])

In [29]:
test1 = pd.DataFrame({'a':[1,2,3,4,5,6]})

In [ ]:
# # convert array in the list first.
# First make the list into a Series:
# se = pd.Series(mylist)

# Then add the values to the DataFrame:
# df['new_col'] = se.values

In [30]:
test1

a
0  1
1  2
2  3
3  4
4  5
5  6

In [31]:
for i in range(5):
    waste = pd.Series(a[:,i])
    test1['a'+str(i)] = waste.values

IndexError: index 5 is out of bounds for axis 1 with size 5

In [32]:
test1

a  a0  a1  a2  a3  a4
0  1  33   0   0   0   0
1  2  33   0   0   0   0
2  3  33   0   0   0   0
3  4  28  13   0   0   0
4  5  47  14  28  39   0
5  6  33   0   0   0   0

In [33]:
test1.dtypes

a     int64
a0    int64
a1    int64
a2    int64
a3    int64
a4    int64
dtype: object

In [ ]:
from tensorflow import keras
from keras.models import Model
from keras.layers import Input, Activation, Dense, Dropout
from keras.layers import concatenate

import numpy as np
import tensorflow as tf

## define parameters

In [2]:
N = 5
M = 3
K = 2
N_u = 5
M_v = 6

## define a_u and a_v as the tensor, because we are not sampling anything

In [3]:
X = np.random.randn(N,M)
a_u = np.random.randn(N,N_u)
a_v = np.random.randn(M,M_v)

# X = tf.convert_to_tensor(X, dtype=tf.float32)
a_u = tf.convert_to_tensor(a_u, dtype=tf.float32)
a_v = tf.convert_to_tensor(a_v, dtype=tf.float32)


def next_batch(batch_size):
    '''
    returnn data of shape [ [batch,N], [batch,M], [batch,1] ]
    fetch index from the matrix of shape [batch,batch]
    '''
    x_idx = np.random.randint(N,size=(batch_size))
    y_idx = np.random.randint(M,size=(batch_size))
    
    rating_label = []
    for i,j in zip(x_idx,y_idx):
        rating_label.append(X[i][j])
#     rating_label = tf.convert_to_tensor(rating_label,dtype=tf.float32)
#     rating_label = tf.reshape(rating_label,shape=[-1,1])
    
#     return Xn, Xm, rating_label
    return x_idx, y_idx, rating_label

## build model

In [4]:
input_user = tf.placeholder(tf.int32,shape=(None,),name='batch-user')
input_user_hot = tf.one_hot(input_user,N, name='one-hot-user')
user_latent = Dense(K,activation='linear', name='user-latent')(input_user_hot)

input_item = tf.placeholder(tf.int32,shape=(None,),name='batch-item')
input_item_hot = tf.one_hot(input_item,M, name='one-hot-item')
item_latent = Dense(K,activation='linear', name='item-latent')(input_item_hot)

info_user = tf.matmul(input_user_hot, a_u)
info_user_latent = Dense(K,activation='linear',name='info-user-latent')(info_user)

info_item = tf.matmul(input_item_hot, a_v)
info_item_latent = Dense(K,activation='linear', name='item-user-latent')(info_item)

In [5]:
input_user, user_latent, input_item, item_latent, info_user_latent, info_item_latent

(<tf.Tensor 'batch-user:0' shape=(?,) dtype=int32>,
 <tf.Tensor 'user-latent/BiasAdd:0' shape=(?, 2) dtype=float32>,
 <tf.Tensor 'batch-item:0' shape=(?,) dtype=int32>,
 <tf.Tensor 'item-latent/BiasAdd:0' shape=(?, 2) dtype=float32>,
 <tf.Tensor 'info-user-latent/BiasAdd:0' shape=(?, 2) dtype=float32>,
 <tf.Tensor 'item-user-latent/BiasAdd:0' shape=(?, 2) dtype=float32>)

In [6]:
pred_rating = tf.matmul(user_latent,tf.transpose(item_latent))#,transpose_item_latent)
pred_rating = tf.diag_part(pred_rating)
pred_rating = tf.reshape(pred_rating,shape=[-1,1])

pred_rating_content = tf.matmul(info_user_latent,tf.transpose(info_item_latent))#,transpose_info_item_latent)
pred_rating_content = tf.diag_part(pred_rating_content)
pred_rating_content = tf.reshape(pred_rating_content, shape=[-1,1])

final_rating = pred_rating + pred_rating_content

In [7]:
final_rating

<tf.Tensor 'add:0' shape=(?, 1) dtype=float32>

## loss function (mse. no classification)

In [8]:
actual = tf.placeholder(tf.float32, shape=(None,),name='rating')

loss = tf.reduce_mean(tf.square(pred_rating - actual))
loss_user = tf.reduce_mean(tf.square(user_latent - info_user_latent))
loss_item = tf.reduce_mean(tf.square(item_latent - info_item_latent))
final_loss = loss + loss_user + loss_item

In [9]:
final_loss

<tf.Tensor 'add_2:0' shape=() dtype=float32>

In [10]:
optimizer = tf.train.AdamOptimizer(0.001).minimize(final_loss)

correct_pred = tf.equal(final_rating, actual)
correct_pred = tf.cast(correct_pred, tf.float32)
accuracy = tf.reduce_mean(correct_pred)

accuracy

<tf.Tensor 'Mean_3:0' shape=() dtype=float32>

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

batch_size = 2
for i in range(10):
    batch = next_batch(batch_size)
    feed_data = {input_user : batch[0], input_item : batch[1], actual : batch[2]}
#     if i % 2 == 0:
#         train_accuracy = accuracy.eval(feed_dict={x: batch[0], y_: batch[1]})
#         print('step %d, training accuracy %g' % (i, train_accuracy))
        
    loss_iter = sess.run(final_loss,feed_dict=feed_data)
    print('step %d, training accuracy %g' % (i, loss_iter))

    sess.run(optimizer, feed_dict=feed_data)

step 0, training accuracy 2.66976
step 1, training accuracy 2.59278
step 2, training accuracy 2.64909
step 3, training accuracy 3.25894
step 4, training accuracy 2.7083
step 5, training accuracy 3.10092
step 6, training accuracy 2.04663
step 7, training accuracy 2.40559
step 8, training accuracy 1.98688
step 9, training accuracy 4.36548
