In [7]:

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 40
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

[[9, 16], [23, 3], [25, 20], [7, 3], [27], [21], [36, 20], [8, 23], [36, 3], [9, 12, 16, 14]]
[[ 9 16  0  0]
 [23  3  0  0]
 [25 20  0  0]
 [ 7  3  0  0]
 [27  0  0  0]
 [21  0  0  0]
 [36 20  0  0]
 [ 8 23  0  0]
 [36  3  0  0]
 [ 9 12 16 14]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 4, 8)              320       
_________________________________________________________________
flatten_3 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 353
Trainable params: 353
Non-trainable params: 0
_________________________________________________________________
None
Accuracy: 100.000000


In [1]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
# from keras.models import Sequential
# from keras.layers import Dense
# from keras.layers import Flatten
# from keras.layers.embeddings import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

Using TensorFlow backend.


[[40, 38], [46, 2], [49, 46], [14, 2], [45], [33], [42, 46], [15, 46], [42, 2], [38, 21, 38, 9]]
[[40 38  0  0]
 [46  2  0  0]
 [49 46  0  0]
 [14  2  0  0]
 [45  0  0  0]
 [33  0  0  0]
 [42 46  0  0]
 [15 46  0  0]
 [42  2  0  0]
 [38 21 38  9]]


In [4]:
[one_hot(d, 20) for d in docs]

[[2, 9],
 [3, 13],
 [13, 18],
 [9, 13],
 [6],
 [13],
 [18, 18],
 [2, 3],
 [18, 13],
 [1, 3, 9, 13]]

In [15]:
mod_docs, docs

([['Well', 'done!'],
  ['Good', 'work'],
  ['Great', 'effort'],
  ['nice', 'work'],
  ['Excellent!'],
  ['Weak'],
  ['Poor', 'effort!'],
  ['not', 'good'],
  ['poor', 'work'],
  ['Could', 'have', 'done', 'better.']],
 ['Well done!',
  'Good work',
  'Great effort',
  'nice work',
  'Excellent!',
  'Weak',
  'Poor effort!',
  'not good',
  'poor work',
  'Could have done better.'])

In [12]:
mod_docs = [i.strip().split() for i in docs]

In [22]:
# [one_hot(d, vocab_size) for d in mod_docs]

In [17]:
import pandas as pd


In [19]:
problems = pd.read_csv('problems_features.csv')
tags = problems['tags'].unique()

In [21]:
list(tags)

[nan,
 'greedy,implementation',
 'constructive algorithms,greedy,math',
 'brute force',
 'dfs and similar,dsu,graphs',
 'implementation',
 'math',
 'math,number theory',
 'brute force,dp,number theory',
 'brute force,dfs and similar,graphs',
 'data structures,expression parsing,math',
 'dfs and similar,greedy',
 'bitmasks,brute force,dfs and similar,expression parsing,implementation',
 'constructive algorithms,divide and conquer,implementation',
 'brute force,implementation,sortings',
 'greedy,shortest paths',
 'combinatorics,constructive algorithms,dfs and similar,graphs',
 'brute force,math,strings',
 'dfs and similar',
 'combinatorics,dp',
 'number theory',
 'dfs and similar,dsu',
 'dp',
 'dfs and similar,graphs,implementation',
 'data structures,dp,implementation',
 'dp,games',
 'hashing,strings',
 'combinatorics,dp,implementation,number theory',
 'data structures',
 'binary search,greedy',
 'constructive algorithms,dp,math',
 'dp,greedy',
 'brute force,math',
 'greedy,two pointers

In [25]:
[one_hot(d, 50) for d in tags[1:]]

[[43, 8],
 [43, 48, 43, 32],
 [41, 45],
 [19, 7, 10, 9, 35],
 [8],
 [32],
 [32, 1, 21],
 [41, 45, 1, 1, 21],
 [41, 45, 19, 7, 10, 35],
 [49, 14, 46, 6, 32],
 [19, 7, 10, 43],
 [5, 41, 45, 19, 7, 10, 46, 6, 8],
 [43, 48, 33, 7, 11, 8],
 [41, 45, 8, 31],
 [43, 13, 3],
 [13, 43, 48, 19, 7, 10, 35],
 [41, 45, 32, 7],
 [19, 7, 10],
 [13, 1],
 [1, 21],
 [19, 7, 10, 9],
 [1],
 [19, 7, 10, 35, 8],
 [49, 14, 1, 8],
 [1, 15],
 [22, 7],
 [13, 1, 8, 1, 21],
 [49, 14],
 [44, 33, 43],
 [43, 48, 1, 32],
 [1, 43],
 [41, 45, 32],
 [43, 35, 10],
 [43, 48, 19, 7, 10, 9, 9],
 [43, 48, 31],
 [19, 7, 10, 1, 35, 7, 9],
 [44, 33, 5, 41, 45, 43, 8, 7],
 [44, 33, 49, 14, 43, 31],
 [43, 48, 19, 7, 10, 9],
 [46, 6, 8],
 [1, 14, 31],
 [5, 41, 45],
 [41, 45, 43, 48, 8],
 [8, 31],
 [43, 8, 7],
 [49, 14, 33, 7, 11],
 [15],
 [41, 45, 31, 35, 10],
 [32, 24, 33],
 [41, 45, 8, 32],
 [41, 45, 43, 48],
 [43],
 [49, 14, 43],
 [13, 19, 7, 10, 35, 9],
 [1, 43, 32],
 [5, 1, 32],
 [43, 40, 20, 3, 29, 31],
 [41, 45, 1, 7],
 [5, 

In [ ]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)
# load the whole embedding into memory
embeddings_index = dict()
f = open('../glove_data/glove.6B/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))



# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

In [ ]:
[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]
 
Loaded 400000 word vectors.
 
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding_1 (Embedding)      (None, 4, 100)            1500
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 401
=================================================================
Total params: 1,901
Trainable params: 401
Non-trainable params: 1,500
_________________________________________________________________
 
 
Accuracy: 100.000000