In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

results = pd.read_csv('data/train/train_submissions.csv')
test = pd.read_csv('data/test_submissions_NeDLEvX.csv')
users = pd.read_csv('cleaned_users.csv')
problems = pd.read_csv('problems_features.csv')
results.shape, test.shape, problems.shape, users.shape

((155295, 3), (66555, 3), (6544, 7), (3571, 11))

In [41]:
temp = test.copy()
test.drop('ID',axis=1,inplace=True)

In [7]:
temp.head(), temp.shape

(     user_id problem_id
 0   user_856  prob_5822
 1  user_2642  prob_2334
 2  user_2557  prob_2920
 3  user_1572  prob_4598
 4   user_295  prob_6139, (66555, 2))

In [8]:
results.shape

(155295, 3)

In [10]:
pd.merge(results,test,on=['user_id','problem_id'])

Empty DataFrame
Columns: [user_id, problem_id, attempts_range, ID]
Index: []

In [42]:
temp2 = pd.DataFrame({'user_id':['user_856']})
temp2

user_id
0  user_856

In [43]:
temp2 = pd.DataFrame({'user_id':['user_856']})
temp2 = pd.merge(temp2,test,on='user_id')
# temp2 = pd.merge(temp2,results,on='user_id')

In [49]:
temp = pd.concat([test, results], axis=0, ignore_index=True)

/home/ankish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [63]:
temp.shape, test.shape, results.shape, 221850-66555

((221850, 3), (66555, 2), (155295, 3), 155295)

In [55]:
temp = pd.concat(test,results,on='user_id')


TypeError: concat() got an unexpected keyword argument 'on'

In [57]:
temp.shape

(221850, 3)

In [62]:
temp.isnull().sum()

attempts_range    66555
problem_id            0
user_id               0
dtype: int64

In [64]:
temp.user_id.unique().shape, temp.problem_id.unique().shape

((3541,), (6212,))

In [67]:
pd.crosstab(temp.user_id,temp.problem_id, temp.attempts_range)

ValueError: values cannot be used without an aggfunc.

In [91]:
data = {'col1':['a','a','b','c'],
        'col2':['d','e','f','g'],
        'col3':[1,2,3,4]}
df = pd.DataFrame(data)

pd.crosstab(df.col1,df.col2)

col2  d  e  f  g
col1            
a     1  1  0  0
b     0  0  1  0
c     0  0  0  1

In [71]:
df.pivot_table(values='col3', index='col1', columns='col2',
    fill_value=0, aggfunc=[np.abs])

absolute         
col2        d  e  f  g
col1                  
a           1  2  0  0
b           0  0  3  0
c           0  0  0  4

In [79]:
del temp2

In [81]:
temp2 = temp.pivot_table(values='attempts_range', index='user_id', columns='problem_id',
                fill_value=0, aggfunc=[np.abs])

In [82]:
temp2.shape

(3529, 5776)

In [92]:
df = df.pivot_table('col3',index='col1',columns='col2')
df

col2    d    e    f    g
col1                    
a     1.0  2.0  NaN  NaN
b     NaN  NaN  3.0  NaN
c     NaN  NaN  NaN  4.0

In [97]:
np.argwhere(df.notnull().values)

array([[0, 0],
       [0, 1],
       [1, 2],
       [2, 3]])

In [96]:
# In [26]: list(df[df.notnull()].stack().index)
# Out[26]: [(0L, '2'), (1L, '0'), (2L, '1')]

# In [27]: df[df.notnull()].stack().index
# Out[27]:
# MultiIndex(levels=[[0, 1, 2], [u'0', u'1', u'2']],
#            labels=[[0, 1, 2], [2, 0, 1]])

# Furthermore, using stack method, NaN are ignored anyway.

# In [28]: list(df.stack().index)
# Out[28]: [(0L, '2'), (1L, '0'), (2L, '1')]

array([ True,  True,  True])

In [ ]:
# import numpy as np

# >>> np.argwhere(df.notnull().values).tolist()
# [[0, 2], [1, 0], [2, 1]]

# If you really want them as tuple pairs, just use a list comprehension:

# >>> [tuple(pair) for pair in np.argwhere(df.notnull().values).tolist()]
# [(0, 2), (1, 0), (2, 1)]

# To get the null locations:

# >>> np.argwhere(df.isnull().values).tolist()
# [[0, 0], [0, 1], [1, 1], [1, 2], [2, 0], [2, 2]]

In [86]:
temp2.columns

MultiIndex(levels=[['absolute'], ['prob_1', 'prob_10', 'prob_100', 'prob_1000', 'prob_1001', 'prob_1002', 'prob_1003', 'prob_1004', 'prob_1005', 'prob_1006', 'prob_1007', 'prob_1008', 'prob_1009', 'prob_101', 'prob_1010', 'prob_1011', 'prob_1012', 'prob_1013', 'prob_1015', 'prob_1016', 'prob_1018', 'prob_1019', 'prob_102', 'prob_1020', 'prob_1021', 'prob_1022', 'prob_1023', 'prob_1024', 'prob_1025', 'prob_1026', 'prob_1027', 'prob_1028', 'prob_1029', 'prob_103', 'prob_1030', 'prob_1031', 'prob_1032', 'prob_1033', 'prob_1034', 'prob_1035', 'prob_1036', 'prob_1037', 'prob_1038', 'prob_104', 'prob_1040', 'prob_1041', 'prob_1042', 'prob_1043', 'prob_1044', 'prob_1045', 'prob_1047', 'prob_1048', 'prob_1049', 'prob_105', 'prob_1050', 'prob_1051', 'prob_1052', 'prob_1053', 'prob_1054', 'prob_1055', 'prob_1057', 'prob_1058', 'prob_1059', 'prob_106', 'prob_1060', 'prob_1061', 'prob_1064', 'prob_1065', 'prob_1066', 'prob_1067', 'prob_1068', 'prob_1069', 'prob_107', 'prob_1070', 'prob_1071', 'pro

In [101]:
problems.columns

Index(['Unnamed: 0', 'problem_id', 'level_type', 'points', 'tags', 'tag_dict',
       'tag_vect'],
      dtype='object')

In [108]:
problems['tag_vect'][3],problems['tag_vect'][4],problems['tag_vect'][7],problems['tag_vect'][10]

('  (0, 35)\t0.643835105031232\n  (0, 33)\t0.7651642683302863',
 '  (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40718947111252246\n  (0, 14)\t0.47255057586028626\n  (0, 13)\t0.47255057586028626\n  (0, 2)\t0.47255057586028626',
 '  (0, 27)\t0.5773502691896257\n  (0, 7)\t0.5773502691896257\n  (0, 6)\t0.5773502691896257',
 '  (0, 55)\t0.41784825617123766\n  (0, 32)\t0.44524222366772453\n  (0, 22)\t0.527226580046366\n  (0, 18)\t0.41784825617123766\n  (0, 17)\t0.41784825617123766')

In [118]:
collect = []
for i in problems['tag_dict']:
    print

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                            ['greedy', 'implementation']
4           ['constructive algorithms', 'greedy', 'math']
5                                                     NaN
6                                                     NaN
7                                         ['brute force']
8                                                     NaN
9                                                     NaN
10                   ['dfs and similar', 'dsu', 'graphs']
11                                     ['implementation']
12                                                    NaN
13                                                    NaN
14                                               ['math']
15                                                    NaN
16                                                    NaN
17            

In [121]:
tt = problems['tags'].unique()

In [132]:
for i in tt[1:]:
    print(i.strip().split(','))

['greedy', 'implementation']
['constructive algorithms', 'greedy', 'math']
['brute force']
['dfs and similar', 'dsu', 'graphs']
['implementation']
['math']
['math', 'number theory']
['brute force', 'dp', 'number theory']
['brute force', 'dfs and similar', 'graphs']
['data structures', 'expression parsing', 'math']
['dfs and similar', 'greedy']
['bitmasks', 'brute force', 'dfs and similar', 'expression parsing', 'implementation']
['constructive algorithms', 'divide and conquer', 'implementation']
['brute force', 'implementation', 'sortings']
['greedy', 'shortest paths']
['combinatorics', 'constructive algorithms', 'dfs and similar', 'graphs']
['brute force', 'math', 'strings']
['dfs and similar']
['combinatorics', 'dp']
['number theory']
['dfs and similar', 'dsu']
['dp']
['dfs and similar', 'graphs', 'implementation']
['data structures', 'dp', 'implementation']
['dp', 'games']
['hashing', 'strings']
['combinatorics', 'dp', 'implementation', 'number theory']
['data structures']
['binary 

In [133]:
collect = [i.strip().split(',') for i in tt[1:]]

In [136]:
collect

[['greedy', 'implementation'],
 ['constructive algorithms', 'greedy', 'math'],
 ['brute force'],
 ['dfs and similar', 'dsu', 'graphs'],
 ['implementation'],
 ['math'],
 ['math', 'number theory'],
 ['brute force', 'dp', 'number theory'],
 ['brute force', 'dfs and similar', 'graphs'],
 ['data structures', 'expression parsing', 'math'],
 ['dfs and similar', 'greedy'],
 ['bitmasks',
  'brute force',
  'dfs and similar',
  'expression parsing',
  'implementation'],
 ['constructive algorithms', 'divide and conquer', 'implementation'],
 ['brute force', 'implementation', 'sortings'],
 ['greedy', 'shortest paths'],
 ['combinatorics', 'constructive algorithms', 'dfs and similar', 'graphs'],
 ['brute force', 'math', 'strings'],
 ['dfs and similar'],
 ['combinatorics', 'dp'],
 ['number theory'],
 ['dfs and similar', 'dsu'],
 ['dp'],
 ['dfs and similar', 'graphs', 'implementation'],
 ['data structures', 'dp', 'implementation'],
 ['dp', 'games'],
 ['hashing', 'strings'],
 ['combinatorics', 'dp', 'im

In [138]:
problems['tags'].unique()

array([nan, 'greedy,implementation',
       'constructive algorithms,greedy,math', 'brute force',
       'dfs and similar,dsu,graphs', 'implementation', 'math',
       'math,number theory', 'brute force,dp,number theory',
       'brute force,dfs and similar,graphs',
       'data structures,expression parsing,math',
       'dfs and similar,greedy',
       'bitmasks,brute force,dfs and similar,expression parsing,implementation',
       'constructive algorithms,divide and conquer,implementation',
       'brute force,implementation,sortings', 'greedy,shortest paths',
       'combinatorics,constructive algorithms,dfs and similar,graphs',
       'brute force,math,strings', 'dfs and similar', 'combinatorics,dp',
       'number theory', 'dfs and similar,dsu', 'dp',
       'dfs and similar,graphs,implementation',
       'data structures,dp,implementation', 'dp,games', 'hashing,strings',
       'combinatorics,dp,implementation,number theory', 'data structures',
       'binary search,greedy', 'co

In [29]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()

u_ids = list(users.user_id.values) + list(results.user_id.values) + list(test.user_id.values)
p_ids = list(problems.problem_id.values) + list(results.problem_id.values) + list(test.problem_id.values)



In [35]:
len(u_ids), np.unique(u_ids).shape,len(p_ids), np.unique(p_ids).shape

(225421, (3571,), 228394, (6544,))

In [38]:
enc.fit(u_ids)
users['user_id_enc'] = enc.transform(users.user_id)
results['user_id_enc'] = enc.transform(results.user_id)
test['user_id_enc'] = enc.transform(test.user_id)

In [39]:
enc.fit(p_ids)
problems['problem_id_enc'] = enc.transform(problems.problem_id)
results['problem_id_enc'] = enc.transform(results.problem_id)
test['problem_id_enc'] = enc.transform(test.problem_id)

In [44]:
print(test.loc[0]['problem_id_enc'])
test.loc[0]

5359


ID                user_856_prob_5822
user_id                     user_856
problem_id                 prob_5822
user_id_enc                     3412
problem_id_enc                  5359
Name: 0, dtype: object

In [46]:
users, problems, results, test

(      Unnamed: 0    user_id  submission_count  problem_solved  contribution  \
 0              0  user_3311                47              40             0   
 1              1  user_3028                63              52             0   
 2              2  user_2268               226             203            -8   
 3              3   user_480               611             490             1   
 4              4   user_650               504             479            12   
 5              5  user_3177                 3               1             0   
 6              6  user_2032               216             199             0   
 7              7  user_3306                 2               1             0   
 8              8  user_1483                91              79             0   
 9              9   user_667                91              71             0   
 10            10  user_2871                12              12             0   
 11            11   user_972            

In [54]:
problems.columns

Index(['Unnamed: 0', 'problem_id', 'level_type', 'points', 'tags', 'tag_dict',
       'tag_vect', 'problem_id_enc'],
      dtype='object')

In [49]:
users.head()

Unnamed: 0    user_id  submission_count  problem_solved  contribution  \
0           0  user_3311                47              40             0   
1           1  user_3028                63              52             0   
2           2  user_2268               226             203            -8   
3           3   user_480               611             490             1   
4           4   user_650               504             479            12   

   follower_count  max_rating   rating          rank  rank_enc  \
0               4     348.337  330.849  intermediate         3   
1              17     405.677  339.450  intermediate         3   
2              24     307.339  284.404      beginner         1   
3              94     525.803  471.330      advanced         0   
4               4     548.739  486.525      advanced         0   

   contribution_abs  user_id_enc  
0                 0         2570  
1                 0         2255  
2                 8         1410  
3                 1         2995  
4                12         3184

In [52]:
u1 = users.drop(['Unnamed: 0', 'user_id','rank','contribution'],axis=1)
u1.to_csv('final_users.csv',index=False)

In [55]:
problems.head()

Unnamed: 0 problem_id level_type  points  \
0           0  prob_3649          H     NaN   
1           1  prob_6191          A     NaN   
2           2  prob_2020          F     NaN   
3           3   prob_313          A   500.0   
4           4   prob_101          A   500.0   

                                  tags  \
0                                  NaN   
1                                  NaN   
2                                  NaN   
3                greedy,implementation   
4  constructive algorithms,greedy,math   

                                        tag_dict  \
0                                            NaN   
1                                            NaN   
2                                            NaN   
3                   ['greedy', 'implementation']   
4  ['constructive algorithms', 'greedy', 'math']   

                                            tag_vect  problem_id_enc  
0                                                NaN            2944  
1                                                NaN            5769  
2                                                NaN            1136  
3    (0, 35)\t0.643835105031232\n  (0, 33)\t0.765...            2368  
4    (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40...              13

In [ ]:
problems['level_type'].fillna('O', inplace=True)
enc.fit(problems['level_type'])
problems['level_enc'] = enc.transform(problems['level_type'])

In [72]:
problems.head()

Unnamed: 0 problem_id level_type  points  \
0           0  prob_3649          H     NaN   
1           1  prob_6191          A     NaN   
2           2  prob_2020          F     NaN   
3           3   prob_313          A   500.0   
4           4   prob_101          A   500.0   

                                  tags  \
0                                  NaN   
1                                  NaN   
2                                  NaN   
3                greedy,implementation   
4  constructive algorithms,greedy,math   

                                        tag_dict  \
0                                            NaN   
1                                            NaN   
2                                            NaN   
3                   ['greedy', 'implementation']   
4  ['constructive algorithms', 'greedy', 'math']   

                                            tag_vect  problem_id_enc  \
0                                                NaN            2944   
1                                                NaN            5769   
2                                                NaN            1136   
3    (0, 35)\t0.643835105031232\n  (0, 33)\t0.765...            2368   
4    (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40...              13   

   level_enc  
0          7  
1          0  
2          5  
3          0  
4          0

In [73]:
problems.columns

Index(['Unnamed: 0', 'problem_id', 'level_type', 'points', 'tags', 'tag_dict',
       'tag_vect', 'problem_id_enc', 'level_enc'],
      dtype='object')

In [76]:
problems.dropna(inplace=True)
problems.drop(['Unnamed: 0', 'problem_id', 'level_type'],axis=1, inplace=True)
problems.head()

points                                 tags  \
3    500.0                greedy,implementation   
4    500.0  constructive algorithms,greedy,math   
7      5.0                          brute force   
10  1000.0           dfs and similar,dsu,graphs   
11   500.0                       implementation   

                                         tag_dict  \
3                    ['greedy', 'implementation']   
4   ['constructive algorithms', 'greedy', 'math']   
7                                 ['brute force']   
10           ['dfs and similar', 'dsu', 'graphs']   
11                             ['implementation']   

                                             tag_vect  problem_id_enc  \
3     (0, 35)\t0.643835105031232\n  (0, 33)\t0.765...            2368   
4     (0, 37)\t0.4053203601812274\n  (0, 33)\t0.40...              13   
7     (0, 27)\t0.5773502691896257\n  (0, 7)\t0.577...            2289   
10    (0, 55)\t0.41784825617123766\n  (0, 32)\t0.4...            3411   
11                                       (0, 35)\t1.0            4363   

    level_enc  
3           0  
4           0  
7           1  
10          1  
11          0

In [77]:
problems.to_csv('final_problems.csv',index=False)

In [78]:
results.head()

user_id problem_id  attempts_range  user_id_enc  problem_id_enc
0   user_232  prob_6507               1         1468            6120
1  user_3568  prob_2994               3         2854            2216
2  user_1600  prob_5071               1          669            4525
3  user_2256   prob_703               1         1397            6216
4  user_2321   prob_356               1         1470            2845

In [79]:
results.drop(['user_id','problem_id'],axis=1)
results.to_csv('final_results.csv',index=False)

In [80]:
test.head()

ID    user_id problem_id  user_id_enc  problem_id_enc
0   user_856_prob_5822   user_856  prob_5822         3412            5359
1  user_2642_prob_2334  user_2642  prob_2334         1826            1484
2  user_2557_prob_2920  user_2557  prob_2920         1731            2135
3  user_1572_prob_4598  user_1572  prob_4598          637            3998
4   user_295_prob_6139   user_295  prob_6139         2167            5711

In [82]:
test.drop(['ID', 'user_id', 'problem_id'],axis=1)
test.to_csv('final_tests.csv',index=False)

In [87]:
np.sort(users.user_id_enc.values)

array([   0,    1,    2, ..., 3568, 3569, 3570])

In [88]:
np.sort(problems.problem_id_enc.values)

array([   3,    5,    6, ..., 6534, 6541, 6543])

In [89]:
users.shape

(3571, 12)

In [90]:
problems.shape

(2546, 6)

In [ ]:
 (6544, 7), (3571, 11))

In [9]:
problems.dropna(inplace=True)

In [12]:
u_ids = users.user_id.unique()
p_ids = problems.problem_id.unique()


In [17]:
u_ids.sort()
p_ids.sort()

In [20]:
p_ids

array(['prob_1000', 'prob_1002', 'prob_1003', ..., 'prob_990', 'prob_997',
       'prob_999'], dtype=object)

In [2]:
u1 = results.user_id.unique()
u2 = test.user_id.unique()
p1 = results.problem_id.unique()
p2 = test.problem_id.unique()


In [3]:
u1.shape, u2.shape, p1.shape, p2.shape

((3529,), (3501,), (5776,), (4716,))

In [5]:
u1.sort()

In [6]:
u1

array(['user_1', 'user_10', 'user_100', ..., 'user_997', 'user_998',
       'user_999'], dtype=object)

In [7]:
u2.sort()
u2

array(['user_1', 'user_10', 'user_100', ..., 'user_997', 'user_998',
       'user_999'], dtype=object)

In [8]:
u1 == u2

/home/ankish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [9]:
collect_u2 = []
for i in u2:
    count = 0
    for j in u1:
        if(i==j):
            count = 1
    if(count == 0):
        print(i)
        collect_u2.append(i)

user_1413
user_1726
user_181
user_2523
user_29
user_3177
user_3384
user_3389
user_3427
user_697
user_742
user_775


In [11]:
# collect_u2

In [12]:
collect_p2 = []
for i in p2:
    count = 0
    for j in p1:
        if(i==j):
            count = 1
    if(count == 0):
        print(i)
        collect_p2.append(i)

prob_168
prob_1977
prob_5189
prob_5981
prob_4729
prob_236
prob_6392
prob_1651
prob_5344
prob_5136
prob_2307
prob_6082
prob_6113
prob_5909
prob_3545
prob_2865
prob_1132
prob_1204
prob_1387
prob_3563
prob_3410
prob_3498
prob_5138
prob_2119
prob_6199
prob_3021
prob_5615
prob_5074
prob_1477
prob_129
prob_2711
prob_4410
prob_3552
prob_3266
prob_4585
prob_1271
prob_6179
prob_285
prob_4958
prob_3862
prob_223
prob_2277
prob_4453
prob_2729
prob_4739
prob_4998
prob_4393
prob_4792
prob_3888
prob_1650
prob_4984
prob_5341
prob_4636
prob_259
prob_817
prob_3500
prob_3517
prob_1572
prob_5862
prob_4743
prob_2687
prob_1753
prob_2971
prob_1369
prob_2616
prob_443
prob_1972
prob_4246
prob_725
prob_2796
prob_3071
prob_1296
prob_5084
prob_177
prob_3433
prob_25
prob_687
prob_6132
prob_5281
prob_5937
prob_3715
prob_6316
prob_4976
prob_575
prob_4762
prob_4483
prob_3058
prob_134
prob_2520
prob_3321
prob_4788
prob_2168
prob_3432
prob_4815
prob_2966
prob_2484
prob_328
prob_5799
prob_6406
prob_2426
prob_855
prob_21

In [14]:
len(collect_u2), len(collect_p2)

(12, 436)

In [15]:
12*436

5232

In [16]:
test.shape

(66555, 3)

In [17]:
results

user_id problem_id  attempts_range
0        user_232  prob_6507               1
1       user_3568  prob_2994               3
2       user_1600  prob_5071               1
3       user_2256   prob_703               1
4       user_2321   prob_356               1
5       user_1569  prob_6064               1
6       user_3293  prob_1237               1
7        user_915  prob_4125               2
8       user_2032  prob_1943               1
9       user_1410  prob_3935               1
10      user_2085  prob_5436               1
11      user_1810  prob_3431               2
12      user_1287  prob_3474               1
13      user_2063  prob_2872               1
14       user_724  prob_6043               2
15        user_88  prob_1914               2
16      user_2269  prob_5641               1
17       user_489   prob_522               1
18      user_1997    prob_32               1
19      user_1929  prob_5731               2
20      user_2084  prob_4232               1
21       user_923  prob_3508               2
22       user_150  prob_6488               1
23      user_2898  prob_1605               1
24      user_3086  prob_2605               1
25      user_2552   prob_534               1
26       user_508  prob_3073               1
27      user_1910  prob_6442               4
28      user_1066   prob_106               1
29      user_1637  prob_1482               1
...           ...        ...             ...
155265  user_1813  prob_1677               1
155266   user_948  prob_4835               1
155267  user_1093  prob_4087               1
155268   user_144  prob_4702               2
155269  user_2407  prob_1396               2
155270  user_2321  prob_4152               2
155271  user_2507  prob_1737               4
155272   user_727   prob_137               1
155273  user_2635  prob_5045               1
155274  user_3114  prob_3445               2
155275  user_2928  prob_5333               1
155276  user_1433  prob_2936               3
155277   user_595    prob_95               1
155278  user_3151  prob_5374               1
155279  user_1346  prob_5995               1
155280  user_1588  prob_5781               1
155281  user_1529  prob_1679               1
155282  user_2815  prob_5880               1
155283  user_3461  prob_5150               1
155284  user_3013  prob_2284               1
155285  user_1563   prob_740               1
155286  user_2838  prob_1181               1
155287  user_1533  prob_5837               2
155288  user_3205  prob_3474               1
155289  user_3271  prob_5932               2
155290  user_2959  prob_2052               1
155291  user_2530  prob_6167               6
155292   user_445  prob_3110               1
155293  user_2337  prob_2685               2
155294  user_1645  prob_4511               2

[155295 rows x 3 columns]