In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, TimeDistributed, RepeatVector

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def generate_sequence(length, max_num):
    return np.random.randint(0,max_num, size=length)

generate_sequence(6,20)

array([ 9, 14,  9,  0,  0, 12])

In [3]:
def one_hot_encode(seq, max_num):
    return np.array([np.eye(max_num)[i] for i in seq])

one_hot_encode(generate_sequence(3,5),5)

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]])

In [4]:
def one_hot_decode(one_hotted_seq, max_num):
    return [np.argmax(i) for i in one_hotted_seq]

one_hot_decode(list(one_hot_encode(generate_sequence(3,5),5)), 5)

[1, 0, 4]

In [44]:
def get_pair(n_in, n_out, max_num):
    in_seq = generate_sequence(n_in, max_num)
    out_seq = in_seq[:n_out]#[0] + [0 for _ in range(2)]
    print out_seq
    out_seq = [out_seq[0],0,0]
    print out_seq
#     print in_seq, out_seq
    x = one_hot_encode(in_seq, max_num)
    y = one_hot_encode(out_seq, max_num)
    
    x = x.reshape(1, x.shape[0], x.shape[1])
    y = y.reshape(1, y.shape[0], y.shape[1])
#     print x,y
    return x, y

x1, y1 = get_pair(3,1, 5)
print x1 
print y1
print x1.shape, y1.shape

[2]
[2, 0, 0]
[[[0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]]
[[[0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0.]]]
(1, 3, 5) (1, 3, 5)


In [46]:
n_features = 5
in_time_steps = 3
out_time_steps = 1
model = Sequential()
model.add(LSTM(100, input_shape = (in_time_steps, n_features)))
model.add(RepeatVector(in_time_steps))
# return_sequences: Boolean. Whether to return the last output 
# in the output sequence, or the full sequence.
model.add(LSTM(100, return_sequences=True))
model.add(TimeDistributed(Dense(n_features, activation='softmax')))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_5 (LSTM)                (None, 100)               42400     
_________________________________________________________________
repeat_vector_3 (RepeatVecto (None, 3, 100)            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 3, 100)            80400     
_________________________________________________________________
time_distributed_3 (TimeDist (None, 3, 5)              505       
Total params: 123,305
Trainable params: 123,305
Non-trainable params: 0
_________________________________________________________________


In [52]:
for epoch in range(1000):
    x,y = get_pair(in_time_steps, 3, n_features)
#     Verbose mode. 0 = silent, 1 = progress bar, 2 = one line per epoch.
    model.fit(x,y, epochs=1, verbose=2)

[4 3 4]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6922 - acc: 0.6667
[2 4 2]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6885 - acc: 0.6667
[4 2 0]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6983 - acc: 0.6667
[1 0 4]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6592 - acc: 0.6667
[2 0 1]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.7037 - acc: 0.6667
[2 3 1]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6899 - acc: 0.6667
[2 2 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6793 - acc: 0.6667
[3 3 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6210 - acc: 0.6667
[3 0 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6365 - acc: 0.6667
[0 3 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.2651 - acc: 1.0000
[3 0 0]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6334 - acc: 0.6667
[4 4 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6860 - acc: 0.6667
[3 2 1]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6310 - acc: 0.6667
[1 2 4]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6449 - acc: 0.6667
[1 2 4]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6448 - acc: 0.6667
[1 4 2]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6444 - acc:

 - 0s - loss: 0.1876 - acc: 1.0000
[3 4 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5486 - acc: 0.6667
[1 0 1]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5017 - acc: 0.6667
[2 0 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5945 - acc: 0.6667
[3 0 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.4644 - acc: 0.6667
[4 3 0]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5768 - acc: 0.6667
[0 4 2]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.2672 - acc: 1.0000
[0 2 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.2725 - acc: 1.0000
[4 1 2]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.6245 - acc: 0.6667
[1 3 1]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5000 - acc: 0.6667
[4 3 0]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5782 - acc: 0.6667
[1 3 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5681 - acc: 0.6667
[0 2 2]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.2514 - acc: 1.0000
[2 4 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5555 - acc: 0.6667
[2 4 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.5450 - acc: 0.6667
[3 3 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.3071 - acc: 1.0000
[1 0 1]
[1, 0, 0]
Ep

[1 0 1]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0079 - acc: 1.0000
[3 0 4]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0213 - acc: 1.0000
[3 1 4]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0146 - acc: 1.0000
[4 0 2]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0290 - acc: 1.0000
[1 4 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0953 - acc: 1.0000
[2 3 0]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.4365 - acc: 0.6667
[4 1 2]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0492 - acc: 1.0000
[4 3 3]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.1657 - acc: 1.0000
[0 4 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0243 - acc: 1.0000
[3 0 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0072 - acc: 1.0000
[2 0 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.1901 - acc: 1.0000
[4 2 4]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0312 - acc: 1.0000
[4 0 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0362 - acc: 1.0000
[1 1 4]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0065 - acc: 1.0000
[2 2 3]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0348 - acc: 1.0000
[1 1 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0061 - acc:

[1 4 0]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0153 - acc: 1.0000
[0 1 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 8.9282e-04 - acc: 1.0000
[1 1 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0024 - acc: 1.0000
[0 2 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0012 - acc: 1.0000
[2 2 1]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0034 - acc: 1.0000
[1 2 4]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0210 - acc: 1.0000
[0 1 0]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 3.4066e-04 - acc: 1.0000
[0 4 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
[2 4 0]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.1276 - acc: 1.0000
[4 3 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0065 - acc: 1.0000
[4 3 0]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0093 - acc: 1.0000
[3 2 1]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0020 - acc: 1.0000
[3 4 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0031 - acc: 1.0000
[2 1 3]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0045 - acc: 1.0000
[3 1 4]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0028 - acc: 1.0000
[4 2 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.007

 - 0s - loss: 0.0011 - acc: 1.0000
[4 1 4]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
[3 4 1]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0024 - acc: 1.0000
[4 1 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0038 - acc: 1.0000
[0 1 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0027 - acc: 1.0000
[2 1 3]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0023 - acc: 1.0000
[0 2 3]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0017 - acc: 1.0000
[1 3 0]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0032 - acc: 1.0000
[3 3 4]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
[0 3 0]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0028 - acc: 1.0000
[0 1 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0022 - acc: 1.0000
[2 0 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0031 - acc: 1.0000
[3 0 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
[2 1 2]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0021 - acc: 1.0000
[0 4 3]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 4.9413e-04 - acc: 1.0000
[3 0 1]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0022 - acc: 1.0000
[1 4 0]
[1, 0, 0

 - 0s - loss: 9.0760e-04 - acc: 1.0000
[4 1 3]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0015 - acc: 1.0000
[1 0 0]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
[3 4 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
[4 1 1]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0027 - acc: 1.0000
[1 3 0]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0018 - acc: 1.0000
[3 4 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0017 - acc: 1.0000
[1 0 2]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
[0 0 0]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 5.3966e-05 - acc: 1.0000
[2 2 0]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 4.7666e-04 - acc: 1.0000
[1 3 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0027 - acc: 1.0000
[1 2 2]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0057 - acc: 1.0000
[1 2 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0037 - acc: 1.0000
[2 2 1]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 5.2168e-04 - acc: 1.0000
[3 3 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 8.9746e-04 - acc: 1.0000
[4 4 2]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 7.1115e-04 - acc: 1.0

[1 1 2]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 6.3019e-04 - acc: 1.0000
[3 1 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 8.2778e-04 - acc: 1.0000
[3 1 1]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 8.2356e-04 - acc: 1.0000
[2 3 2]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 6.2515e-04 - acc: 1.0000
[1 0 0]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
[3 4 3]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 7.4396e-04 - acc: 1.0000
[4 2 3]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0013 - acc: 1.0000
[0 3 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 5.1280e-04 - acc: 1.0000
[2 4 3]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0033 - acc: 1.0000
[4 1 4]
[4, 0, 0]
Epoch 1/1
 - 0s - loss: 7.3557e-04 - acc: 1.0000
[0 4 2]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 1.9019e-04 - acc: 1.0000
[0 0 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 4.7588e-05 - acc: 1.0000
[2 1 1]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0056 - acc: 1.0000
[2 1 0]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0028 - acc: 1.0000
[0 4 3]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 1.8659e-04 - acc: 1.0000
[4 1 3]
[4, 0, 

 - 0s - loss: 0.0011 - acc: 1.0000
[2 3 3]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
[1 1 3]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 4.0335e-04 - acc: 1.0000
[3 3 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 3.7731e-04 - acc: 1.0000
[2 0 2]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 4.4745e-04 - acc: 1.0000
[3 1 4]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 8.2146e-04 - acc: 1.0000
[3 0 2]
[3, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
[0 1 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 3.2095e-04 - acc: 1.0000
[0 0 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 3.5129e-05 - acc: 1.0000
[1 4 1]
[1, 0, 0]
Epoch 1/1
 - 0s - loss: 5.6462e-04 - acc: 1.0000
[0 3 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 2.7173e-04 - acc: 1.0000
[0 1 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
[0 1 1]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
[0 0 0]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 3.2566e-05 - acc: 1.0000
[2 1 4]
[2, 0, 0]
Epoch 1/1
 - 0s - loss: 0.0014 - acc: 1.0000
[0 2 4]
[0, 0, 0]
Epoch 1/1
 - 0s - loss: 2.509

In [53]:
total, correct = 100,0
for _ in range(total):
    x,y = get_pair(in_time_steps, 3, n_features)
    y_hat = model.predict(x, verbose=0)
    if np.array_equal(one_hot_decode(y[0], n_features), one_hot_decode(y_hat[0], n_features)):
        correct += 1
print 'Accuracy: %.2f%%' %(float(correct)/float(total)*100.0)

[2 3 3]
[2, 0, 0]
[1 3 3]
[1, 0, 0]
[1 2 1]
[1, 0, 0]
[1 4 2]
[1, 0, 0]
[3 2 3]
[3, 0, 0]
[3 1 1]
[3, 0, 0]
[2 0 2]
[2, 0, 0]
[2 3 0]
[2, 0, 0]
[3 3 1]
[3, 0, 0]
[2 3 4]
[2, 0, 0]
[1 2 1]
[1, 0, 0]
[0 4 1]
[0, 0, 0]
[3 2 0]
[3, 0, 0]
[1 1 1]
[1, 0, 0]
[2 4 3]
[2, 0, 0]
[0 2 1]
[0, 0, 0]
[1 1 2]
[1, 0, 0]
[4 0 4]
[4, 0, 0]
[3 2 1]
[3, 0, 0]
[3 0 2]
[3, 0, 0]
[4 3 1]
[4, 0, 0]
[4 3 1]
[4, 0, 0]
[3 0 0]
[3, 0, 0]
[1 3 0]
[1, 0, 0]
[0 2 0]
[0, 0, 0]
[2 2 0]
[2, 0, 0]
[4 0 3]
[4, 0, 0]
[2 4 4]
[2, 0, 0]
[2 3 3]
[2, 0, 0]
[1 3 0]
[1, 0, 0]
[1 3 0]
[1, 0, 0]
[3 3 0]
[3, 0, 0]
[4 2 3]
[4, 0, 0]
[0 4 1]
[0, 0, 0]
[3 4 4]
[3, 0, 0]
[3 2 0]
[3, 0, 0]
[1 4 1]
[1, 0, 0]
[1 3 0]
[1, 0, 0]
[1 2 4]
[1, 0, 0]
[3 1 4]
[3, 0, 0]
[0 0 4]
[0, 0, 0]
[3 1 4]
[3, 0, 0]
[0 1 2]
[0, 0, 0]
[0 2 4]
[0, 0, 0]
[1 4 4]
[1, 0, 0]
[1 4 1]
[1, 0, 0]
[1 0 4]
[1, 0, 0]
[1 2 1]
[1, 0, 0]
[1 0 0]
[1, 0, 0]
[1 2 4]
[1, 0, 0]
[4 4 3]
[4, 0, 0]
[2 2 3]
[2, 0, 0]
[4 4 4]
[4, 0, 0]
[2 1 4]
[2, 0, 0]
[3 0 3]
[3, 0, 0]
[1 2 0]
[1

In [56]:
# spot check some examples
for _ in range(10):
    x,y = get_pair(in_time_steps, out_time_steps, n_features)
    yhat = model.predict(x, verbose=0)
#     print y_hat
    print('Expected:', one_hot_decode(y[0],n_features), 'Predicted', one_hot_decode(yhat[0],n_features))

[4]
[4, 0, 0]
('Expected:', [4, 0, 0], 'Predicted', [4, 0, 0])
[2]
[2, 0, 0]
('Expected:', [2, 0, 0], 'Predicted', [2, 0, 0])
[1]
[1, 0, 0]
('Expected:', [1, 0, 0], 'Predicted', [1, 0, 0])
[1]
[1, 0, 0]
('Expected:', [1, 0, 0], 'Predicted', [1, 0, 0])
[4]
[4, 0, 0]
('Expected:', [4, 0, 0], 'Predicted', [4, 0, 0])
[1]
[1, 0, 0]
('Expected:', [1, 0, 0], 'Predicted', [1, 0, 0])
[2]
[2, 0, 0]
('Expected:', [2, 0, 0], 'Predicted', [2, 0, 0])
[2]
[2, 0, 0]
('Expected:', [2, 0, 0], 'Predicted', [2, 0, 0])
[3]
[3, 0, 0]
('Expected:', [3, 0, 0], 'Predicted', [3, 0, 0])
[1]
[1, 0, 0]
('Expected:', [1, 0, 0], 'Predicted', [1, 0, 0])
