In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
import os
os.listdir()

['final_xgboost_prepared.csv',
 'cleaned.csv',
 'Y_valid.npy',
 'gartner_final # 31488 rows (train) + 6910 rows (test).ipynb',
 'submission.ipynb',
 '.ipynb_checkpoints',
 'submission.csv',
 'sample_submission84eff4f.csv',
 'gartner_data_cleaning.ipynb',
 'dataset',
 'cleaned_new.csv',
 'submission1.csv',
 'final_float_int_cleaned.csv',
 'Untitled.ipynb',
 'final_data.pkl',
 'complete_16_dtypes.pkl',
 'final_cleaned.csv',
 'X_test.npy',
 'final_16_dtypes.pkl',
 'final_float_int_cleaned_new.csv',
 'final_done_dtype_16_all_category.pkl',
 'Y_train.npy',
 'final_16_dtypes.csv',
 'real_data',
 'gartner_xgboost # 31488 - 2 rows (train) + 6910 rows (test).ipynb',
 'X_valid.npy',
 'X_train.pickle.npy',
 'Re_ gartner_data_cleaning']

In [4]:
data = pd.read_csv('cleaned_new.csv')
data.describe()

/home/ankish/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (16,31,46,64,76,86,108,118) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  1:1_Meeting_0  1:1_Meeting_1  1:1_Meeting_10  \
count  38398.00000   38398.000000   38398.000000    38398.000000   
mean   13532.00487       0.010704       0.011745        0.009480   
std     9526.82512       0.130369       0.137667        0.125478   
min        0.00000       0.000000       0.000000        0.000000   
25%     4799.25000       0.000000       0.000000        0.000000   
50%    12288.50000       0.000000       0.000000        0.000000   
75%    21887.75000       0.000000       0.000000        0.000000   
max    31487.00000       3.000000       3.000000        4.000000   

       1:1_Meeting_11  1:1_Meeting_2  1:1_Meeting_3  1:1_Meeting_4  \
count    38398.000000   38398.000000   38398.000000   38398.000000   
mean         0.010573       0.013204       0.011120       0.009792   
std          0.133635       0.147229       0.131726       0.123992   
min          0.000000       0.000000       0.000000       0.000000   
25%          0.000000       0.000000       0.000000       0.000000   
50%          0.000000       0.000000       0.000000       0.000000   
75%          0.000000       0.000000       0.000000       0.000000   
max          5.000000       3.000000       3.000000       3.000000   

       1:1_Meeting_5  1:1_Meeting_6      ...       View_Peer_11   View_Peer_2  \
count   38398.000000   38398.000000      ...       38398.000000  38398.000000   
mean        0.011615       0.010495      ...           0.854680      0.769936   
std         0.138714       0.127559      ...           3.616089      3.058082   
min         0.000000       0.000000      ...           0.000000      0.000000   
25%         0.000000       0.000000      ...           0.000000      0.000000   
50%         0.000000       0.000000      ...           0.000000      0.000000   
75%         0.000000       0.000000      ...           0.000000      0.000000   
max         3.000000       2.000000      ...         295.000000    128.000000   

        View_Peer_3   View_Peer_4   View_Peer_5   View_Peer_6   View_Peer_7  \
count  38398.000000  38398.000000  38398.000000  38398.000000  38398.000000   
mean       0.756914      0.800276      0.812334      0.790848      0.843794   
std        2.823916      2.893250      3.257929      3.109898      3.290412   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max       96.000000    159.000000    158.000000    180.000000    197.000000   

        View_Peer_8   View_Peer_9          test  
count  38398.000000  38398.000000  38398.000000  
mean       0.804261      0.843612      2.531408  
std        2.967354      3.355265      0.564362  
min        0.000000      0.000000      0.000000  
25%        0.000000      0.000000      2.000000  
50%        0.000000      0.000000      3.000000  
75%        0.000000      0.000000      3.000000  
max      166.000000    244.000000      4.000000  

[8 rows x 108 columns]

In [5]:
data.head()

Unnamed: 0  1:1_Meeting_0  1:1_Meeting_1  1:1_Meeting_10  1:1_Meeting_11  \
0           0            0.0            0.0             0.0             0.0   
1           1            0.0            0.0             0.0             0.0   
2           2            0.0            0.0             0.0             0.0   
3           3            0.0            0.0             0.0             0.0   
4           4            0.0            0.0             0.0             0.0   

   1:1_Meeting_2  1:1_Meeting_3  1:1_Meeting_4  1:1_Meeting_5  1:1_Meeting_6  \
0            0.0            0.0            0.0            0.0            0.0   
1            0.0            0.0            0.0            0.0            0.0   
2            0.0            0.0            0.0            0.0            0.0   
3            0.0            0.0            0.0            0.0            0.0   
4            0.0            0.0            0.0            0.0            0.0   

   ...   View_Peer_3  View_Peer_4  View_Peer_5  View_Peer_6  View_Peer_7  \
0  ...           0.0          0.0          1.0          0.0          0.0   
1  ...           0.0          0.0          0.0          0.0          0.0   
2  ...           0.0          0.0          0.0          0.0          0.0   
3  ...           0.0          0.0          1.0          0.0          0.0   
4  ...           0.0          0.0          1.0          0.0          0.0   

   View_Peer_8 View_Peer_9  View_Peer_Last120_Flag(Y/N)    target  test  
0          0.0         1.0                            Y  Retained     4  
1          0.0         0.0                            Y   Dropped     4  
2          0.0         0.0                            N  Retained     4  
3          0.0         0.0                            Y  Retained     4  
4          0.0         0.0                            N   Dropped     4  

[5 rows x 120 columns]

In [6]:
data.dtypes

Unnamed: 0                         int64
1:1_Meeting_0                    float64
1:1_Meeting_1                    float64
1:1_Meeting_10                   float64
1:1_Meeting_11                   float64
1:1_Meeting_2                    float64
1:1_Meeting_3                    float64
1:1_Meeting_4                    float64
1:1_Meeting_5                    float64
1:1_Meeting_6                    float64
1:1_Meeting_7                    float64
1:1_Meeting_8                    float64
1:1_Meeting_9                    float64
Conference_Attended_0            float64
Conference_Attended_1            float64
Conference_Attended_10           float64
Conference_Attended_11            object
Conference_Attended_2            float64
Conference_Attended_3            float64
Conference_Attended_4            float64
Conference_Attended_5            float64
Conference_Attended_6            float64
Conference_Attended_7            float64
Conference_Attended_8            float64
Conference_Atten

In [8]:
a = data.isnull().sum()

In [9]:
col_index_list = []
for index,ai in enumerate(a):
    if ai is not 0:
        print(index,ai)
        col_index_list.append(index)

57 4862
60 6910
118 6910


In [10]:
col_index_name = []
for i in col_index_list:
    col_index_name.append(data.columns[i])

In [11]:
col_index_name

['Multi-Year In', 'Retention Status', 'target']

In [9]:
data[col_index_name]

Multi-Year In  Retention Status    target
0                0.0               1.0  Retained
1                0.0               0.0   Dropped
2                1.0               1.0  Retained
3                1.0               1.0  Retained
4                0.0               0.0   Dropped
5                0.0               1.0  Retained
6                0.0               1.0  Retained
7                0.0               1.0  Retained
8                1.0               1.0  Retained
9                0.0               1.0  Retained
10               0.0               1.0  Retained
11               0.0               0.0   Dropped
12               0.0               1.0  Retained
13               0.0               0.0   Dropped
14               0.0               1.0  Retained
15               1.0               1.0  Retained
16               1.0               1.0  Retained
17               0.0               0.0   Dropped
18               0.0               0.0   Dropped
19               0.0               1.0  Retained
20               1.0               1.0  Retained
21               0.0               1.0  Retained
22               0.0               0.0   Dropped
23               0.0               1.0  Retained
24               0.0               1.0  Retained
25               0.0               0.0   Dropped
26               1.0               1.0  Retained
27               0.0               0.0   Dropped
28               1.0               1.0  Retained
29               3.0               0.0   Dropped
...              ...               ...       ...
38368            2.0               NaN       NaN
38369            2.0               NaN       NaN
38370            NaN               NaN       NaN
38371            2.0               NaN       NaN
38372            NaN               NaN       NaN
38373            NaN               NaN       NaN
38374            NaN               NaN       NaN
38375            2.0               NaN       NaN
38376            NaN               NaN       NaN
38377            NaN               NaN       NaN
38378            2.0               NaN       NaN
38379            2.0               NaN       NaN
38380            NaN               NaN       NaN
38381            NaN               NaN       NaN
38382            NaN               NaN       NaN
38383            NaN               NaN       NaN
38384            2.0               NaN       NaN
38385            NaN               NaN       NaN
38386            NaN               NaN       NaN
38387            2.0               NaN       NaN
38388            NaN               NaN       NaN
38389            2.0               NaN       NaN
38390            2.0               NaN       NaN
38391            2.0               NaN       NaN
38392            NaN               NaN       NaN
38393            2.0               NaN       NaN
38394            NaN               NaN       NaN
38395            3.0               NaN       NaN
38396            NaN               NaN       NaN
38397            NaN               NaN       NaN

[38398 rows x 3 columns]

In [12]:
data['Inquiry Eligible Flag (Y/N)'].isnull().sum()

0

In [12]:
data['Inquiry Eligible Flag (Y/N)'].unique()

array([nan, 'Y', 'N', '0', 'Core Research'], dtype=object)

In [19]:
# from sklearn.preprocessing import LabelEncoder

# enc = LabelEncoder()

In [22]:
# enc_labels1 = enc.fit_transform(data['Inquiry Eligible Flag (Y/N)'])
# enc_mappings1 = {index: label for index, label in 
#                   enumerate(enc.classes_)}
# print(enc_labels1,enc_mappings1)

# data['Inquiry Eligible Flag (Y/N)'] = LabelEncoder().fit_transform(data['Inquiry Eligible Flag (Y/N)'])

In [23]:
# df.iloc[0, df.columns.get_loc('col2')] = 100

In [24]:
# data.iloc[28832]['Inquiry Eligible Flag (Y/N)'] = 'c'#,data['Inquiry Eligible Flag (Y/N)']] 

In [25]:
# data.loc[28832]['Inquiry Eligible Flag (Y/N)'] = 'c'

In [ ]:
# train['test'] = train['Inquiry Eligible Flag (Y/N)'].map(dict(No=0,Yes=1))

In [26]:
data['Inquiry Eligible Flag (Y/N)'] = data['Inquiry Eligible Flag (Y/N)'].fillna('a')

In [27]:
data['test'] = data['Inquiry Eligible Flag (Y/N)'].map(dict(No=0,Yes=1,a=2,0=3,Core Research=4))

SyntaxError: invalid syntax (<ipython-input-27-475507b43ad8>, line 1)

In [30]:
data[data['Inquiry Eligible Flag (Y/N)'] == 'Core Research']

Unnamed: 0  Retention Status    Region  Plan Start Year-month  \
28832       28832                 1  Region C                 201711   
29432       29432                 1  Region A                 201711   

       Transaction Year-month Contract Ending Date Seat Registration Date  \
28832                  201803           2018-03-31             2017-04-03   
29432                  201803           2018-03-31             2017-04-03   

       Contract Multi-Year (Y/N)  Multi-Year In  Multi Year Length  ...    \
28832                          1              1                3.0  ...     
29432                          1              1                3.0  ...     

      1:1_Meeting_4 1:1_Meeting_3  1:1_Meeting_2  1:1_Meeting_1  \
28832           0.0           0.0            0.0            0.0   
29432           0.0           0.0            0.0            0.0   

       1:1_Meeting_0  Month_Contract_Period  Onboarding Satus(Y/N)  test_code  \
28832            0.0                    NaN                      1          1   
29432            0.0                    NaN                      1          1   

       test  test1  
28832   0.0    0.0  
29432  12.0   12.0  

[2 rows x 125 columns]

In [32]:
data[data['Inquiry Eligible Flag (Y/N)'] == 'Core Research']

Unnamed: 0  Retention Status    Region  Plan Start Year-month  \
28832       28832                 1  Region C                 201711   
29432       29432                 1  Region A                 201711   

       Transaction Year-month Contract Ending Date Seat Registration Date  \
28832                  201803           2018-03-31             2017-04-03   
29432                  201803           2018-03-31             2017-04-03   

       Contract Multi-Year (Y/N)  Multi-Year In  Multi Year Length  ...    \
28832                          1              1                3.0  ...     
29432                          1              1                3.0  ...     

      1:1_Meeting_4 1:1_Meeting_3  1:1_Meeting_2  1:1_Meeting_1  \
28832           0.0           0.0            0.0            0.0   
29432           0.0           0.0            0.0            0.0   

       1:1_Meeting_0  Month_Contract_Period  Onboarding Satus(Y/N)  test_code  \
28832            0.0                    NaN                      1          1   
29432            0.0                    NaN                      1          1   

       test  test1  
28832   0.0    0.0  
29432  12.0   12.0  

[2 rows x 125 columns]

In [33]:
data = data.drop([28832,29432],axis=0)

In [35]:
data.columns

Index(['Unnamed: 0', 'Retention Status', 'Region', 'Plan Start Year-month',
       'Transaction Year-month', 'Contract Ending Date',
       'Seat Registration Date', 'Contract Multi-Year (Y/N)', 'Multi-Year In',
       'Multi Year Length',
       ...
       '1:1_Meeting_4', '1:1_Meeting_3', '1:1_Meeting_2', '1:1_Meeting_1',
       '1:1_Meeting_0', 'Month_Contract_Period', 'Onboarding Satus(Y/N)',
       'test_code', 'test', 'test1'],
      dtype='object', length=125)

In [37]:
data.shape

(31486, 125)

In [38]:
data1 = data.copy()

In [41]:
col_index_name.remove('Inquiry Eligible Flag (Y/N)')

In [42]:
col_index_name

['Contract Ending Date',
 'Seat Registration Date',
 'Multi Year Length',
 'Month_Contract_Period']

In [43]:
del data

In [45]:
data1['Inquiry Eligible Flag (Y/N)'].unique()

array(['a', 'Y', 'N', '0'], dtype=object)

In [46]:
data['Inquiry Eligible Flag (Y/N)'] = data['Inquiry Eligible Flag (Y/N)'].map(dict(N=0,Y=1,0=2,a=3))

SyntaxError: keyword can't be an expression (<ipython-input-46-8012c870056a>, line 1)

In [49]:
data1[data1['Inquiry Eligible Flag (Y/N)'] == '0']

Unnamed: 0  Retention Status    Region  Plan Start Year-month  \
22224       22224                 0  Region D                 201606   
22228       22228                 1  Region D                 201606   
22259       22259                 1  Region A                 201606   
22303       22303                 0  Region C                 201606   
22314       22314                 1  Region D                 201606   
22611       22611                 1  Region C                 201606   
22621       22621                 1  Region A                 201606   
22727       22727                 1  Region D                 201606   
22905       22905                 1  Region C                 201606   
23255       23255                 1  Region C                 201606   
24442       24442                 1  Region B                 201608   
24443       24443                 1  Region D                 201608   
24463       24463                 1  Region A                 201608   
24464       24464                 1  Region A                 201608   
24534       24534                 1  Region B                 201608   
24535       24535                 1  Region A                 201608   
24576       24576                 1  Region D                 201608   
24577       24577                 1  Region A                 201608   
24729       24729                 1  Region A                 201608   
24730       24730                 1  Region A                 201608   
24824       24824                 1  Region C                 201608   
24825       24825                 1  Region D                 201608   
24890       24890                 1  Region C                 201608   
24891       24891                 1  Region A                 201608   
24911       24911                 1  Region B                 201608   
24912       24912                 1  Region D                 201608   
24951       24951                 1  Region A                 201608   
24952       24952                 1  Region A                 201608   
24953       24953                 1  Region C                 201608   
24954       24954                 1  Region B                 201608   
25156       25156                 1  Region D                 201608   
25157       25157                 1  Region D                 201608   
25160       25160                 1  Region C                 201608   
25161       25161                 1  Region B                 201608   
25162       25162                 1  Region D                 201608   
25163       25163                 1  Region B                 201608   
25170       25170                 1  Region B                 201608   
25171       25171                 1  Region A                 201608   
25225       25225                 1  Region D                 201608   
25226       25226                 1  Region C                 201608   
25229       25229                 1  Region C                 201608   
25230       25230                 1  Region A                 201608   
25760       25760                 0  Region C                 201608   
25761       25761                 0  Region B                 201608   
25943       25943                 1  Region A                 201608   
25944       25944                 1  Region B                 201608   
26119       26119                 1  Region C                 201608   
26120       26120                 1  Region B                 201608   
26149       26149                 0  Region C                 201608   
26150       26150                 0  Region B                 201608   
26271       26271                 1  Region A                 201608   
26272       26272                 1  Region A                 201608   
26312       26312                 1  Region C                 201608   
26313       26313                 1  Region D                 201608   
26894       26894                 1  Region B  

In [54]:
data1['Inquiry Eligible Flag (Y/N)'].value_counts()

N    15533
Y    14741
a     1152
0       60
Name: Inquiry Eligible Flag (Y/N), dtype: int64

In [58]:
data1.groupby(['Inquiry Eligible Flag (Y/N)'])['Retention Status'].unique()

Inquiry Eligible Flag (Y/N)
0    [0, 1]
N    [1, 0]
Y    [0, 1]
a    [1, 0]
Name: Retention Status, dtype: object

In [59]:
data1.groupby(['Retention Status'])['Inquiry Eligible Flag (Y/N)'].unique()

Retention Status
0    [a, Y, N, 0]
1    [a, Y, N, 0]
Name: Inquiry Eligible Flag (Y/N), dtype: object

In [61]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()

enc_labels1 = enc.fit_transform(data1['Inquiry Eligible Flag (Y/N)'])
enc_mappings1 = {index: label for index, label in 
                  enumerate(enc.classes_)}
print(enc_labels1,enc_mappings1)



[3 3 3 ... 2 1 1] {0: '0', 1: 'N', 2: 'Y', 3: 'a'}


In [62]:
data1['Inquiry Eligible Flag (Y/N)'] = LabelEncoder().fit_transform(data1['Inquiry Eligible Flag (Y/N)'])

In [63]:
data1['Inquiry Eligible Flag (Y/N)'].unique()

array([3, 2, 1, 0])

In [67]:
data1 = data1.drop('Unnamed: 0',axis=1)

In [68]:
data1.columns

Index(['Retention Status', 'Region', 'Plan Start Year-month',
       'Transaction Year-month', 'Contract Ending Date',
       'Seat Registration Date', 'Contract Multi-Year (Y/N)', 'Multi-Year In',
       'Multi Year Length', 'Inquiry Eligible Flag (Y/N)',
       ...
       '1:1_Meeting_4', '1:1_Meeting_3', '1:1_Meeting_2', '1:1_Meeting_1',
       '1:1_Meeting_0', 'Month_Contract_Period', 'Onboarding Satus(Y/N)',
       'test_code', 'test', 'test1'],
      dtype='object', length=124)

In [69]:
data1.to_csv('final_cleaned.csv')

In [71]:
data1.shape

(31486, 124)

In [72]:
data1 = data1.drop(col_index_name,axis=1)

In [73]:
data1.shape

(31486, 120)

In [74]:
data1.to_pickle('final_data.pkl')

NameError: name 'col_names' is not defined

In [3]:
data = pd.read_csv('dataset/train.csv')

/home/ankish/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (12,27,42,57,71,84,108) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
data.head()

Retention Status Unique Client Key    Region  Plan Start Year-month  \
0         Retained          SER11243  Region D                 201609   
1          Dropped          SER11245  Region B                 201609   
2         Retained          SER11246  Region B                 201609   
3         Retained          SER11247  Region A                 201609   
4          Dropped          SER11250  Region C                 201609   

   Transaction Year-month Business Unit (EU or HTTP) Contract Ending Date  \
0                  201701                         EU           2017-01-31   
1                  201701                         EU           2017-01-31   
2                  201701                         EU           2017-01-31   
3                  201701                         EU           2017-01-31   
4                  201701                         EU           2017-01-31   

  Seat Registration Date Contract Multi-Year (Y/N)  Multi-Year In  \
0                    NaN                         N              0   
1                    NaN                         N              0   
2                    NaN                         Y              1   
3                    NaN                         Y              1   
4                    NaN                         N              0   

           ...            1:1_Meeting_6 1:1_Meeting_5 1:1_Meeting_4  \
0          ...                      NaN           NaN           NaN   
1          ...                      NaN           NaN           NaN   
2          ...                      NaN           NaN           NaN   
3          ...                      NaN           NaN           NaN   
4          ...                      NaN           NaN           NaN   

   1:1_Meeting_3  1:1_Meeting_2  1:1_Meeting_1  1:1_Meeting_0  \
0            NaN            NaN            NaN            NaN   
1            NaN            NaN            NaN            NaN   
2            NaN            NaN            NaN            NaN   
3            NaN            NaN            NaN            NaN   
4            NaN            NaN            NaN            NaN   

   Total_1:1_Meeting_12  Month_Contract_Period  Onboarding Satus(Y/N)  
0                   NaN                   11.0                     No  
1                   NaN                   11.0                     No  
2                   NaN                   11.0                    Yes  
3                   NaN                   12.0                    Yes  
4                   NaN                   11.0                     No  

[5 rows x 124 columns]

In [5]:
data.dtypes

Retention Status                     object
Unique Client Key                    object
Region                               object
Plan Start Year-month                 int64
Transaction Year-month                int64
Business Unit (EU or HTTP)           object
Contract Ending Date                 object
Seat Registration Date               object
Contract Multi-Year (Y/N)            object
Multi-Year In                         int64
Multi Year Length                   float64
Inquiry Eligible Flag (Y/N)          object
Document_Read_12                     object
Document_Read_11                    float64
Document_Read_10                    float64
Document_Read_9                     float64
Document_Read_8                     float64
Document_Read_7                     float64
Document_Read_6                     float64
Document_Read_5                     float64
Document_Read_4                     float64
Document_Read_3                     float64
Document_Read_2                 

In [7]:
data['Testimonial_1'].unique()

array([nan,  3.,  1.,  2.,  8.,  0.,  5.,  4.])

In [8]:
data['Testimonial_0'].unique()

array([nan, 1.0, 2.0, 0.0, '0', '2', '1', '3', 'RED'], dtype=object)

In [9]:
test = pd.read_csv('dataset/test.csv')

In [11]:
test['Testimonial_0'].unique()

array([nan,  1.,  2.])

In [12]:
test.dtypes

Unique Client Key                    object
Region                               object
Plan Start Year-month                 int64
Transaction Year-month                int64
Business Unit (EU or HTTP)           object
Contract Ending Date                 object
Seat Registration Date               object
Contract Multi-Year (Y/N)            object
Multi-Year In                       float64
Multi Year Length                   float64
Inquiry Eligible Flag (Y/N)          object
Document_Read_12                    float64
Document_Read_11                    float64
Document_Read_10                    float64
Document_Read_9                     float64
Document_Read_8                     float64
Document_Read_7                     float64
Document_Read_6                     float64
Document_Read_5                     float64
Document_Read_4                     float64
Document_Read_3                     float64
Document_Read_2                     float64
Document_Read_1                 